pkm_trn_src/src/Entity/Pokemon.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PokemonRepository")
 */
class Pokemon
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $team_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $base_exp_value;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image_path;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ability;

    
    public function __construct()
    {
        $this->created_at = new \DateTime();
    }
    
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    public function getId()
    {
        return $this->id;
    }

    public function getTeamId()
    {
        return $this->team_id;
    }

    public function setTeamId(int $team_id): self
    {
        $this->team_id = $team_id;

        return $this;
    }

    public function getName()
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getBaseExpValue()
    {
        return $this->base_exp_value;
    }

    public function setBaseExpValue(int $base_exp_value): self
    {
        $this->base_exp_value = $base_exp_value;

        return $this;
    }

    public function getImagePath()
    {
        return $this->image_path;
    }

    public function setImagePath(string $image_path): self
    {
        $this->image_path = $image_path;

        return $this;
    }

    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getAbility()
    {
        return $this->ability;
    }

    public function setAbility(string $ability): self
    {
        $this->ability = $ability;

        return $this;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }
}

pkm_trn_src/src/Form/PokemonType.php
<?php

namespace App\Form;

use App\Entity\Pokemon;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;

class PokemonType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            //            ->add('team_id')
            ->add('name', TextType::class)
            ->add('base_exp_value', IntegerType::class, ['label' => 'Base Experience'])
//            ->add('image_path', TextType::class)
//            ->add('created_at')
            ->add('ability', TextType::class)
            ->add('type', TextType::class)
                
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Pokemon::class,
        ]);
    }
}

pkm_trn_src/src/Controller/PokemonController.php
<?php

namespace App\Controller;

use App\Entity\Pokemon;
use App\Entity\Team;
use App\Form\PokemonType;
use App\Form\CreatePokemonType;
use \App\Repository\PokemonRepository;
use \App\Repository\TeamRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/pokemon")
 */
class PokemonController extends AbstractController
{
    /**
     * @Route("/", name="pokemon_index", methods={"GET"})
     */
    public function index(PokemonRepository $pokemonRepository): Response
    {
        return $this->render('pokemon/index.html.twig', [
            'pokemon' => $pokemonRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new/{name}", name="pokemon_new", methods={"GET","POST"})
     */
    public function newP(Request $request,$name=''): Response
    {
        $rd='';
        $team_id = '';
        $pokemon = new Pokemon();
        $pokemonRep = $this->getDoctrine()->getRepository(Pokemon::class);
        $teamRep = $this->getDoctrine()->getRepository(Team::class);
        $form = $this->createForm(CreatePokemonType::class, $pokemon);
        $form->handleRequest($request);
        $rnd = rand(1,20);
        
        if ($form->isSubmitted() && $form->isValid()) {
            
            $teamValues= $teamRep->findOneByField('name',$name);//get team id
            $pokemon->setTeamId($teamValues['id']);
                        
            $pkmItems = $pokemonRep->countItemsFindByNameTeamid($pokemon->getName(),$pokemon->getTeamId());
		
	    if($pkmItems>0){
                return $this->redirectToRoute('pokemon_new',['name'=>$name]);
            }
            /*creation of a new pokemon*/
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($pokemon);
            $entityManager->flush();
            
            //save image on the local filesystem
            $dataF = $form->getData();
            $pokemonRep->getAndSaveImage($dataF->getImagePath());
            
            //flush cache
             $cacheDriver = new \Doctrine\Common\Cache\ArrayCache();
             $deleted = $cacheDriver->deleteAll();
             
            return $this->redirectToRoute('team_index');
        }

        return $this->render('pokemon/new.html.twig', [
            'pokemon' => $pokemon,
            'rnd' => $rnd,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="pokemon_show", methods={"GET"})
     */
    public function show(Pokemon $pokemon): Response
    {
        return $this->render('pokemon/show.html.twig', [
            'pokemon' => $pokemon,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="pokemon_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Pokemon $pokemon): Response
    {
        $form = $this->createForm(PokemonType::class, $pokemon);
        $form->handleRequest($request);
        $teamRep = $this->getDoctrine()->getRepository(Team::class);
        $pokemonRep = $this->getDoctrine()->getRepository(Pokemon::class);

        if ($form->isSubmitted() && $form->isValid()) {
            $pkmItems = $pokemonRep->countItemsFindByNameTeamid($pokemon->getName(),$pokemon->getTeamId());
		
	    if($pkmItems>0){
                return $this->redirectToRoute('pokemon_new',['name'=>$name]);
            }

            $this->getDoctrine()->getManager()->flush();
            
            //flush cache
             $cacheDriver = new \Doctrine\Common\Cache\ArrayCache();
             $deleted = $cacheDriver->deleteAll();
             
            return $this->redirectToRoute('team_index');
        }

        return $this->render('pokemon/edit.html.twig', [
            'pokemon' => $pokemon,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="pokemon_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Pokemon $pokemon): Response
    {
        
        if ($this->isCsrfTokenValid('delete'.$pokemon->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $pokemonRep = $this->getDoctrine()->getRepository(Pokemon::class);
            $teamRep = $this->getDoctrine()->getRepository(Team::class);
            $pkmItems = $pokemonRep->countItems($pokemon->getTeamId());
            
            if($pkmItems==1){//Deletion of team related
                $teamRep->delete($pokemon->getTeamId());
            }
            
            //pokemon deletion
            $entityManager->remove($pokemon);
            $entityManager->flush();
        }

        return $this->redirectToRoute('team_index');
    }
}

pkm_trn_src/templates/pokemon/_delete_form.html.twig
<form method="post" action="{{ path('pokemon_delete', {'id': pokemon.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ pokemon.id) }}">
    <button class="btn" style="background-color: red;color: white;">Delete</button>
</form>

pkm_trn_src/templates/pokemon/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

pkm_trn_src/templates/pokemon/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Pokemon{% endblock %}

{% block body %}
    <h1>Edit Pokemon</h1>

    {{ include('pokemon/_form.html.twig', {'button_label': 'Update'}) }}
    
    <p>
    {{ include('pokemon/_delete_form.html.twig') }}
    </p>
    
    <a href="{{ path('team_index') }}"><button style="background-color: green;color: white;">back to list</button></a> &nbsp; &nbsp; 
{% endblock %}

pkm_trn_src/templates/pokemon/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pokemon index{% endblock %}

{% block body %}
    <h1>Pokemon index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Team_id</th>
                <th>Name</th>
                <th>Base_exp_value</th>
                <th>Image_path</th>
                <th>Created_at</th>
                <th>Ability</th>
                <th>Type</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for pokemon in pokemon %}
            <tr>
                <td>{{ pokemon.id }}</td>
                <td>{{ pokemon.teamId }}</td>
                <td>{{ pokemon.name }}</td>
                <td>{{ pokemon.baseExpValue }}</td>
                
                <td><img src="{{ asset('{{ pokemon.image_path }}')}}" alt=""/></td>
                <td>{{ pokemon.createdAt ? pokemon.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ pokemon.ability }}</td>
                <td>{{ pokemon.type }}</td>
                <td>
                    <a href="{{ path('pokemon_show', {'id': pokemon.id}) }}">show</a>
                    <a href="{{ path('pokemon_edit', {'id': pokemon.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('pokemon_new') }}">Create new</a>
{% endblock %}

pkm_trn_src/templates/pokemon/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Pokemon{% endblock %}

{% block body %}
    <h1>Create new Pokemon</h1>
<p>
    <button onclick="getPkm()">Gotta Catch 'Em All</button>
</p>
    {{ include('pokemon/_form.html.twig') }}

{% endblock %}
{% block javascripts %}
    <script type="text/javascript"> var rnd = {{rnd}};  

	{# Docker compose deletes js files in public/bundle/ folder#}
	{# Workaround for Docker compose #}
	function getPkm(){

            $.get( "https://pokeapi.co/api/v2/pokemon/"+rnd )
            .done(function( data ) {
                var abilities;
                var types;
                
                abilities = abilityToString(data.abilities);
                types = typeToString(data.types);
                setValue("create_pokemon_name",data.name);
                setValue("create_pokemon_base_exp_value",data.base_experience);
                setValue("create_pokemon_image_path",rnd+'.png');
                setValue("create_pokemon_ability",abilities);
                setValue("create_pokemon_type",types);
            });
        }

	function setValue(id,value){
            $("#"+id).val(value);
        }
        
        function abilityToString(data){
            var r = '';
            for(var i=0;i<data.length;i++){
                r += data[i].ability.name+' - ';
            }
            return r;
        }
        
        function typeToString(data){
            var r = '';
            for(var i=0;i<data.length;i++){
                r += data[i].type.name+' - ';
            }
            return r;
        }
</script>
{% endblock %}

pkm_trn_src/templates/pokemon/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pokemon{% endblock %}

{% block body %}
    <h1>Pokemon</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ pokemon.id }}</td>
            </tr>
            <tr>
                <th>Team_id</th>
                <td>{{ pokemon.teamId }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ pokemon.name }}</td>
            </tr>
            <tr>
                <th>Base_exp_value</th>
                <td>{{ pokemon.baseExpValue }}</td>
            </tr>
            <tr>
                <th>Image_path</th>
                <td>{{ pokemon.imagePath }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ pokemon.createdAt ? pokemon.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Ability</th>
                <td>{{ pokemon.ability }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ pokemon.type }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('pokemon_index') }}">back to list</a>

    <a href="{{ path('pokemon_edit', {'id': pokemon.id}) }}">edit</a>

    {{ include('pokemon/_delete_form.html.twig') }}
{% endblock %}